#!/bin/bash

# see https://leetcode.com/problems/sliding-window-maximum

nums=(1 3 -1 -3 5 3 6 7)
k=3
# nums=(1)
# k=1
res=()

for ((i = 0; i <= ${#nums[@]} - k; i++)); do
    max=${nums[i]}
    for ((j = i + 1; j < i + k; j++)); do
        if [[ ${nums[j]} -gt $max ]]; then
            max=${nums[j]}
        fi
    done
    res+=($max)
done

echo "${res[@]}"
